[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
winnow = { version = "0.6.20", features = ["debug"] }
